name: Deploy
on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest
    name: Deploy
    steps:
      - uses: actions/checkout@v4

      # Bunのインストール
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest  # 最新バージョンをインストールする場合

      # ビルドステップ
      - name: Build
        run: bun run build

      # デプロイステップ
      - name: Deploy
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CF_API_TOKEN }}
          accountId: ${{ secrets.CF_ACCOUNT_ID }}